name: auto_issues

on:
  schedule:
  - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build-go
        run: |
          go env -w GO111MODULE=on
          cd actions && go build -o monthly monthly.go
      - name: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: cd actions &&./monthly -c ./issuesinfo.json
